package specview

import (
	"fmt"
	"time"
)

// Language represents the target language for spec-view generation.
// Any language name is accepted (e.g., "Korean", "English", "Chinese", "Spanish").
type Language string

// SpecViewRequest represents a request to generate a spec-view document.
type SpecViewRequest struct {
	AnalysisID      string
	ForceRegenerate bool     // skip cache and create new version
	Language        Language
	ModelID         string   // optional: AI model override
	UserID          string   // required: document owner
}

func (r SpecViewRequest) Validate() error {
	if r.AnalysisID == "" {
		return fmt.Errorf("%w: analysis ID is required", ErrInvalidInput)
	}
	if r.UserID == "" {
		return fmt.Errorf("%w: user ID is required", ErrInvalidInput)
	}
	if r.Language == "" {
		return fmt.Errorf("%w: language is required", ErrInvalidInput)
	}
	if !r.Language.IsValid() {
		return fmt.Errorf("%w: unsupported language: %s", ErrInvalidInput, r.Language)
	}
	return nil
}

// IsValid checks if the language is not empty.
func (l Language) IsValid() bool {
	return l != ""
}

// SpecViewResult represents the result of spec-view generation.
type SpecViewResult struct {
	AnalysisContext     *AnalysisContext    // repository context for logging
	BehaviorCacheStats  *BehaviorCacheStats // Phase 2 behavior cache statistics (nil on document cache hit)
	CacheHit            bool
	ContentHash         []byte
	DocumentID          string
}

// BehaviorCacheStats represents cache hit/miss statistics for Phase 2 behavior cache.
type BehaviorCacheStats struct {
	CachedBehaviors    int     // count of behaviors retrieved from cache
	GeneratedBehaviors int     // count of behaviors generated by AI
	HitRate            float64 // cache hit rate (0.0 ~ 1.0)
	TotalBehaviors     int     // total behavior count
}

// Phase1Input represents input for domain classification (Phase 1).
type Phase1Input struct {
	AnalysisID string // for chunk caching across retries
	Files      []FileInfo
	Language   Language
}

// FileInfo represents a test file with its tests and domain hints.
type FileInfo struct {
	DomainHints *DomainHints
	Framework   string
	Path        string
	Tests       []TestInfo
}

// DomainHints provides contextual information for domain classification.
type DomainHints struct {
	Calls   []string // Function/method calls within tests
	Imports []string // Module imports in the test file
}

// TestInfo represents a single test within a file.
type TestInfo struct {
	Index      int    // unique identifier for cross-referencing in Phase1Output.FeatureGroup.TestIndices
	Name       string
	SuitePath  string // nested suite path (e.g., "SuiteA > SuiteB")
	TestCaseID string // FK to test_cases table
}

// Phase1Output represents the result of domain classification.
type Phase1Output struct {
	Domains []DomainGroup
}

// DomainGroup represents a classified domain with its features.
type DomainGroup struct {
	Confidence  float64
	Description string
	Features    []FeatureGroup
	Name        string
}

// FeatureGroup represents a feature within a domain.
type FeatureGroup struct {
	Confidence  float64
	Description string
	Name        string
	TestIndices []int // references to Phase1Input.Files[*].Tests[*].Index
}

// Phase2Input represents input for test name conversion (Phase 2).
type Phase2Input struct {
	DomainContext string // domain context for better conversion
	FeatureName   string
	Language      Language
	Tests         []TestForConversion
}

// TestForConversion represents a test to be converted.
type TestForConversion struct {
	Index int
	Name  string
}

// Phase2Output represents the result of test name conversion.
type Phase2Output struct {
	Behaviors []BehaviorSpec
}

// BehaviorSpec represents a converted test behavior.
type BehaviorSpec struct {
	Confidence  float64
	Description string
	TestIndex   int
}

// Phase3Input represents input for executive summary generation (Phase 3).
type Phase3Input struct {
	Domains  []Domain
	Language Language
}

// Phase3Output represents the result of executive summary generation.
type Phase3Output struct {
	Summary string
}

// SpecDocument represents the final spec-view document (4-table hierarchy root).
type SpecDocument struct {
	AnalysisID       string
	ContentHash      []byte
	CreatedAt        time.Time
	Domains          []Domain
	ExecutiveSummary string
	ID               string
	Language         Language
	ModelID          string
	UserID           string
	Version          int32
}

// Domain represents a domain within a spec document.
type Domain struct {
	Confidence  float64
	Description string
	Features    []Feature
	ID          string
	Name        string
}

// Feature represents a feature within a domain.
type Feature struct {
	Behaviors   []Behavior
	Confidence  float64
	Description string
	ID          string
	Name        string
}

// Behavior represents a behavior (converted test) within a feature.
type Behavior struct {
	Confidence   float64
	Description  string
	ID           string
	OriginalName string // original test name before conversion
	TestCaseID   string // FK to test_cases table
}

// AnalysisContext provides repository identification context for logging.
type AnalysisContext struct {
	Host  string
	Owner string
	Repo  string
}

// BehaviorCacheEntry represents a cached behavior conversion result.
// Cache key is generated from: test_name + suite_path + file_path + language + model_id
type BehaviorCacheEntry struct {
	CacheKeyHash []byte // SHA-256 hash of cache key components
	Description  string // converted behavior description
}

// BehaviorCacheKey represents the components used to generate a cache key hash.
type BehaviorCacheKey struct {
	FilePath  string
	Language  Language
	ModelID   string
	SuitePath string
	TestName  string
}

// TaxonomyInput represents input for Stage 1 taxonomy extraction.
// Contains file metadata without test names to minimize token usage.
type TaxonomyInput struct {
	AnalysisID string
	Files      []TaxonomyFileInfo
	Language   Language
}

// TaxonomyFileInfo represents file metadata for taxonomy extraction.
// Excludes test names to keep Stage 1 prompt small (~15K tokens for 500 files).
type TaxonomyFileInfo struct {
	DomainHints *DomainHints
	Index       int    // file index for cross-referencing in TaxonomyOutput
	Path        string
	TestCount   int
}

// TaxonomyOutput represents the result of Stage 1 taxonomy extraction.
// Defines the fixed domain structure for Stage 2 assignment.
type TaxonomyOutput struct {
	Domains []TaxonomyDomain `json:"domains"`
}

// TaxonomyDomain represents a domain in the extracted taxonomy.
type TaxonomyDomain struct {
	Description string            `json:"description"`
	Features    []TaxonomyFeature `json:"features"`
	Name        string            `json:"name"`
}

// TaxonomyFeature represents a feature within a taxonomy domain.
// FileIndices indicates which files belong to this feature.
type TaxonomyFeature struct {
	FileIndices []int  `json:"file_indices"`
	Name        string `json:"name"`
}

// AssignmentBatch represents a batch of tests for Stage 2 assignment.
// Each batch contains ~100 tests to be assigned to the fixed taxonomy.
type AssignmentBatch struct {
	BatchIndex int
	Tests      []TestForAssignment
}

// TestForAssignment represents a test to be assigned to a domain/feature.
type TestForAssignment struct {
	FilePath  string
	Index     int // global test index for cross-referencing
	Name      string
	SuitePath string
}

// AssignmentOutput represents the result of Stage 2 test assignment.
// Uses compact field names to minimize output tokens.
type AssignmentOutput struct {
	Assignments []TestAssignment `json:"a"`
}

// TestAssignment represents a single test-to-domain/feature assignment.
// Uses compact field names (d=domain, f=feature, t=test indices).
type TestAssignment struct {
	Domain      string `json:"d"`
	Feature     string `json:"f"`
	TestIndices []int  `json:"t"`
}
