// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisStatus string

const (
	AnalysisStatusPending   AnalysisStatus = "pending"
	AnalysisStatusRunning   AnalysisStatus = "running"
	AnalysisStatusCompleted AnalysisStatus = "completed"
	AnalysisStatusFailed    AnalysisStatus = "failed"
)

func (e *AnalysisStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalysisStatus(s)
	case string:
		*e = AnalysisStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalysisStatus: %T", src)
	}
	return nil
}

type NullAnalysisStatus struct {
	AnalysisStatus AnalysisStatus `json:"analysis_status"`
	Valid          bool           `json:"valid"` // Valid is true if AnalysisStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalysisStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnalysisStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalysisStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalysisStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalysisStatus), nil
}

type GithubAccountType string

const (
	GithubAccountTypeOrganization GithubAccountType = "organization"
	GithubAccountTypeUser         GithubAccountType = "user"
)

func (e *GithubAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GithubAccountType(s)
	case string:
		*e = GithubAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for GithubAccountType: %T", src)
	}
	return nil
}

type NullGithubAccountType struct {
	GithubAccountType GithubAccountType `json:"github_account_type"`
	Valid             bool              `json:"valid"` // Valid is true if GithubAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGithubAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.GithubAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GithubAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGithubAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GithubAccountType), nil
}

type OauthProvider string

const (
	OauthProviderGithub OauthProvider = "github"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider `json:"oauth_provider"`
	Valid         bool          `json:"valid"` // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type PlanTier string

const (
	PlanTierFree       PlanTier = "free"
	PlanTierPro        PlanTier = "pro"
	PlanTierProPlus    PlanTier = "pro_plus"
	PlanTierEnterprise PlanTier = "enterprise"
)

func (e *PlanTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanTier(s)
	case string:
		*e = PlanTier(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanTier: %T", src)
	}
	return nil
}

type NullPlanTier struct {
	PlanTier PlanTier `json:"plan_tier"`
	Valid    bool     `json:"valid"` // Valid is true if PlanTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanTier) Scan(value interface{}) error {
	if value == nil {
		ns.PlanTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanTier), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive   SubscriptionStatus = "active"
	SubscriptionStatusCanceled SubscriptionStatus = "canceled"
	SubscriptionStatusExpired  SubscriptionStatus = "expired"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type TestStatus string

const (
	TestStatusActive  TestStatus = "active"
	TestStatusSkipped TestStatus = "skipped"
	TestStatusTodo    TestStatus = "todo"
	TestStatusFocused TestStatus = "focused"
	TestStatusXfail   TestStatus = "xfail"
)

func (e *TestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestStatus(s)
	case string:
		*e = TestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestStatus: %T", src)
	}
	return nil
}

type NullTestStatus struct {
	TestStatus TestStatus `json:"test_status"`
	Valid      bool       `json:"valid"` // Valid is true if TestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestStatus), nil
}

type UsageEventType string

const (
	UsageEventTypeSpecview UsageEventType = "specview"
	UsageEventTypeAnalysis UsageEventType = "analysis"
)

func (e *UsageEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsageEventType(s)
	case string:
		*e = UsageEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for UsageEventType: %T", src)
	}
	return nil
}

type NullUsageEventType struct {
	UsageEventType UsageEventType `json:"usage_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if UsageEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsageEventType) Scan(value interface{}) error {
	if value == nil {
		ns.UsageEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsageEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsageEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsageEventType), nil
}

type Analysis struct {
	ID            pgtype.UUID        `json:"id"`
	CodebaseID    pgtype.UUID        `json:"codebase_id"`
	CommitSha     string             `json:"commit_sha"`
	BranchName    pgtype.Text        `json:"branch_name"`
	Status        AnalysisStatus     `json:"status"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TotalSuites   int32              `json:"total_suites"`
	TotalTests    int32              `json:"total_tests"`
	CommittedAt   pgtype.Timestamptz `json:"committed_at"`
	ParserVersion string             `json:"parser_version"`
}

type AtlasSchemaRevision struct {
	Version         string             `json:"version"`
	Description     string             `json:"description"`
	Type            int64              `json:"type"`
	Applied         int64              `json:"applied"`
	Total           int64              `json:"total"`
	ExecutedAt      pgtype.Timestamptz `json:"executed_at"`
	ExecutionTime   int64              `json:"execution_time"`
	Error           pgtype.Text        `json:"error"`
	ErrorStmt       pgtype.Text        `json:"error_stmt"`
	Hash            string             `json:"hash"`
	PartialHashes   []byte             `json:"partial_hashes"`
	OperatorVersion string             `json:"operator_version"`
}

type BehaviorCach struct {
	ID                   pgtype.UUID        `json:"id"`
	CacheKeyHash         []byte             `json:"cache_key_hash"`
	ConvertedDescription string             `json:"converted_description"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ClassificationCach struct {
	ID           pgtype.UUID        `json:"id"`
	ContentHash  []byte             `json:"content_hash"`
	Language     string             `json:"language"`
	ModelID      string             `json:"model_id"`
	Phase1Output []byte             `json:"phase1_output"`
	TestIndexMap []byte             `json:"test_index_map"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Codebasis struct {
	ID             pgtype.UUID        `json:"id"`
	Host           string             `json:"host"`
	Owner          string             `json:"owner"`
	Name           string             `json:"name"`
	DefaultBranch  pgtype.Text        `json:"default_branch"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastViewedAt   pgtype.Timestamptz `json:"last_viewed_at"`
	ExternalRepoID string             `json:"external_repo_id"`
	IsStale        bool               `json:"is_stale"`
	IsPrivate      bool               `json:"is_private"`
}

type GithubAppInstallation struct {
	ID               pgtype.UUID        `json:"id"`
	InstallationID   int64              `json:"installation_id"`
	AccountType      GithubAccountType  `json:"account_type"`
	AccountID        int64              `json:"account_id"`
	AccountLogin     string             `json:"account_login"`
	AccountAvatarUrl pgtype.Text        `json:"account_avatar_url"`
	InstallerUserID  pgtype.UUID        `json:"installer_user_id"`
	SuspendedAt      pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type GithubOrganization struct {
	ID          pgtype.UUID        `json:"id"`
	GithubOrgID int64              `json:"github_org_id"`
	Login       string             `json:"login"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	HtmlUrl     pgtype.Text        `json:"html_url"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OauthAccount struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Provider         OauthProvider      `json:"provider"`
	ProviderUserID   string             `json:"provider_user_id"`
	ProviderUsername pgtype.Text        `json:"provider_username"`
	AccessToken      pgtype.Text        `json:"access_token"`
	Scope            pgtype.Text        `json:"scope"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	Replaces  pgtype.UUID        `json:"replaces"`
}

type RiverClient struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `json:"river_client_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaxWorkers       int64              `json:"max_workers"`
	Metadata         []byte             `json:"metadata"`
	NumJobsCompleted int64              `json:"num_jobs_completed"`
	NumJobsRunning   int64              `json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `json:"id"`
	State        RiverJobState      `json:"state"`
	Attempt      int16              `json:"attempt"`
	MaxAttempts  int16              `json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	Priority     int16              `json:"priority"`
	Args         []byte             `json:"args"`
	AttemptedBy  []string           `json:"attempted_by"`
	Errors       [][]byte           `json:"errors"`
	Kind         string             `json:"kind"`
	Metadata     []byte             `json:"metadata"`
	Queue        string             `json:"queue"`
	Tags         []string           `json:"tags"`
	UniqueKey    []byte             `json:"unique_key"`
	UniqueStates pgtype.Bits        `json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LeaderID  string             `json:"leader_id"`
	Name      string             `json:"name"`
}

type RiverQueue struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SpecBehavior struct {
	ID                   pgtype.UUID        `json:"id"`
	FeatureID            pgtype.UUID        `json:"feature_id"`
	SourceTestCaseID     pgtype.UUID        `json:"source_test_case_id"`
	OriginalName         string             `json:"original_name"`
	ConvertedDescription string             `json:"converted_description"`
	SortOrder            int32              `json:"sort_order"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type SpecDocument struct {
	ID               pgtype.UUID        `json:"id"`
	AnalysisID       pgtype.UUID        `json:"analysis_id"`
	ContentHash      []byte             `json:"content_hash"`
	Language         string             `json:"language"`
	ExecutiveSummary pgtype.Text        `json:"executive_summary"`
	ModelID          string             `json:"model_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Version          int32              `json:"version"`
	UserID           pgtype.UUID        `json:"user_id"`
}

type SpecDomain struct {
	ID                       pgtype.UUID        `json:"id"`
	DocumentID               pgtype.UUID        `json:"document_id"`
	Name                     string             `json:"name"`
	Description              pgtype.Text        `json:"description"`
	SortOrder                int32              `json:"sort_order"`
	ClassificationConfidence pgtype.Numeric     `json:"classification_confidence"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type SpecFeature struct {
	ID          pgtype.UUID        `json:"id"`
	DomainID    pgtype.UUID        `json:"domain_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionPlan struct {
	ID                   pgtype.UUID        `json:"id"`
	Tier                 PlanTier           `json:"tier"`
	SpecviewMonthlyLimit pgtype.Int4        `json:"specview_monthly_limit"`
	AnalysisMonthlyLimit pgtype.Int4        `json:"analysis_monthly_limit"`
	RetentionDays        pgtype.Int4        `json:"retention_days"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	MonthlyPrice         pgtype.Int4        `json:"monthly_price"`
}

type SystemConfig struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TestCase struct {
	ID         pgtype.UUID `json:"id"`
	SuiteID    pgtype.UUID `json:"suite_id"`
	Name       string      `json:"name"`
	LineNumber pgtype.Int4 `json:"line_number"`
	Status     TestStatus  `json:"status"`
	Tags       []byte      `json:"tags"`
	Modifier   pgtype.Text `json:"modifier"`
}

type TestFile struct {
	ID          pgtype.UUID `json:"id"`
	AnalysisID  pgtype.UUID `json:"analysis_id"`
	FilePath    string      `json:"file_path"`
	Framework   pgtype.Text `json:"framework"`
	DomainHints []byte      `json:"domain_hints"`
}

type TestSuite struct {
	ID         pgtype.UUID `json:"id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Name       string      `json:"name"`
	LineNumber pgtype.Int4 `json:"line_number"`
	Depth      int32       `json:"depth"`
	FileID     pgtype.UUID `json:"file_id"`
}

type UsageEvent struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	EventType   UsageEventType     `json:"event_type"`
	AnalysisID  pgtype.UUID        `json:"analysis_id"`
	DocumentID  pgtype.UUID        `json:"document_id"`
	QuotaAmount int32              `json:"quota_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Username     string             `json:"username"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TokenVersion int32              `json:"token_version"`
}

type UserAnalysisHistory struct {
	UserID     pgtype.UUID        `json:"user_id"`
	AnalysisID pgtype.UUID        `json:"analysis_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         pgtype.UUID        `json:"id"`
}

type UserBookmark struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CodebaseID pgtype.UUID        `json:"codebase_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ID         pgtype.UUID        `json:"id"`
}

type UserGithubOrgMembership struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Role      pgtype.Text        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGithubRepository struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	GithubRepoID    int64              `json:"github_repo_id"`
	Name            string             `json:"name"`
	FullName        string             `json:"full_name"`
	HtmlUrl         string             `json:"html_url"`
	Description     pgtype.Text        `json:"description"`
	DefaultBranch   pgtype.Text        `json:"default_branch"`
	Language        pgtype.Text        `json:"language"`
	Visibility      string             `json:"visibility"`
	IsPrivate       bool               `json:"is_private"`
	Archived        bool               `json:"archived"`
	Disabled        bool               `json:"disabled"`
	Fork            bool               `json:"fork"`
	StargazersCount int32              `json:"stargazers_count"`
	PushedAt        pgtype.Timestamptz `json:"pushed_at"`
	SourceType      string             `json:"source_type"`
	OrgID           pgtype.UUID        `json:"org_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserSpecviewHistory struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserSubscription struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	PlanID             pgtype.UUID        `json:"plan_id"`
	Status             SubscriptionStatus `json:"status"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CanceledAt         pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
