// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisStatus string

const (
	AnalysisStatusPending   AnalysisStatus = "pending"
	AnalysisStatusRunning   AnalysisStatus = "running"
	AnalysisStatusCompleted AnalysisStatus = "completed"
	AnalysisStatusFailed    AnalysisStatus = "failed"
)

func (e *AnalysisStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalysisStatus(s)
	case string:
		*e = AnalysisStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalysisStatus: %T", src)
	}
	return nil
}

type NullAnalysisStatus struct {
	AnalysisStatus AnalysisStatus `json:"analysis_status"`
	Valid          bool           `json:"valid"` // Valid is true if AnalysisStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalysisStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnalysisStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalysisStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalysisStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalysisStatus), nil
}

type OauthProvider string

const (
	OauthProviderGithub OauthProvider = "github"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider `json:"oauth_provider"`
	Valid         bool          `json:"valid"` // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type TestStatus string

const (
	TestStatusActive  TestStatus = "active"
	TestStatusSkipped TestStatus = "skipped"
	TestStatusTodo    TestStatus = "todo"
	TestStatusFocused TestStatus = "focused"
	TestStatusXfail   TestStatus = "xfail"
)

func (e *TestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestStatus(s)
	case string:
		*e = TestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestStatus: %T", src)
	}
	return nil
}

type NullTestStatus struct {
	TestStatus TestStatus `json:"test_status"`
	Valid      bool       `json:"valid"` // Valid is true if TestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestStatus), nil
}

type Analysis struct {
	ID           pgtype.UUID        `json:"id"`
	CodebaseID   pgtype.UUID        `json:"codebase_id"`
	CommitSha    string             `json:"commit_sha"`
	BranchName   pgtype.Text        `json:"branch_name"`
	Status       AnalysisStatus     `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	TotalSuites  int32              `json:"total_suites"`
	TotalTests   int32              `json:"total_tests"`
}

type AtlasSchemaRevision struct {
	Version         string             `json:"version"`
	Description     string             `json:"description"`
	Type            int64              `json:"type"`
	Applied         int64              `json:"applied"`
	Total           int64              `json:"total"`
	ExecutedAt      pgtype.Timestamptz `json:"executed_at"`
	ExecutionTime   int64              `json:"execution_time"`
	Error           pgtype.Text        `json:"error"`
	ErrorStmt       pgtype.Text        `json:"error_stmt"`
	Hash            string             `json:"hash"`
	PartialHashes   []byte             `json:"partial_hashes"`
	OperatorVersion string             `json:"operator_version"`
}

type Codebasis struct {
	ID             pgtype.UUID        `json:"id"`
	Host           string             `json:"host"`
	Owner          string             `json:"owner"`
	Name           string             `json:"name"`
	DefaultBranch  pgtype.Text        `json:"default_branch"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	LastViewedAt   pgtype.Timestamptz `json:"last_viewed_at"`
	ExternalRepoID string             `json:"external_repo_id"`
	IsStale        bool               `json:"is_stale"`
}

type GithubOrganization struct {
	ID          pgtype.UUID        `json:"id"`
	GithubOrgID int64              `json:"github_org_id"`
	Login       string             `json:"login"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	HtmlUrl     pgtype.Text        `json:"html_url"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OauthAccount struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Provider         OauthProvider      `json:"provider"`
	ProviderUserID   string             `json:"provider_user_id"`
	ProviderUsername pgtype.Text        `json:"provider_username"`
	AccessToken      pgtype.Text        `json:"access_token"`
	Scope            pgtype.Text        `json:"scope"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RiverClient struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `json:"river_client_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaxWorkers       int64              `json:"max_workers"`
	Metadata         []byte             `json:"metadata"`
	NumJobsCompleted int64              `json:"num_jobs_completed"`
	NumJobsRunning   int64              `json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `json:"id"`
	State        RiverJobState      `json:"state"`
	Attempt      int16              `json:"attempt"`
	MaxAttempts  int16              `json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	Priority     int16              `json:"priority"`
	Args         []byte             `json:"args"`
	AttemptedBy  []string           `json:"attempted_by"`
	Errors       [][]byte           `json:"errors"`
	Kind         string             `json:"kind"`
	Metadata     []byte             `json:"metadata"`
	Queue        string             `json:"queue"`
	Tags         []string           `json:"tags"`
	UniqueKey    []byte             `json:"unique_key"`
	UniqueStates pgtype.Bits        `json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LeaderID  string             `json:"leader_id"`
	Name      string             `json:"name"`
}

type RiverQueue struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TestCase struct {
	ID         pgtype.UUID `json:"id"`
	SuiteID    pgtype.UUID `json:"suite_id"`
	Name       string      `json:"name"`
	LineNumber pgtype.Int4 `json:"line_number"`
	Status     TestStatus  `json:"status"`
	Tags       []byte      `json:"tags"`
	Modifier   pgtype.Text `json:"modifier"`
}

type TestSuite struct {
	ID         pgtype.UUID `json:"id"`
	AnalysisID pgtype.UUID `json:"analysis_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Name       string      `json:"name"`
	FilePath   string      `json:"file_path"`
	LineNumber pgtype.Int4 `json:"line_number"`
	Framework  pgtype.Text `json:"framework"`
	Depth      int32       `json:"depth"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       pgtype.Text        `json:"email"`
	Username    string             `json:"username"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserAnalysisHistory struct {
	UserID     pgtype.UUID        `json:"user_id"`
	AnalysisID pgtype.UUID        `json:"analysis_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         pgtype.UUID        `json:"id"`
}

type UserBookmark struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CodebaseID pgtype.UUID        `json:"codebase_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ID         pgtype.UUID        `json:"id"`
}

type UserGithubOrgMembership struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Role      pgtype.Text        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGithubRepository struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	GithubRepoID    int64              `json:"github_repo_id"`
	Name            string             `json:"name"`
	FullName        string             `json:"full_name"`
	HtmlUrl         string             `json:"html_url"`
	Description     pgtype.Text        `json:"description"`
	DefaultBranch   pgtype.Text        `json:"default_branch"`
	Language        pgtype.Text        `json:"language"`
	Visibility      string             `json:"visibility"`
	IsPrivate       bool               `json:"is_private"`
	Archived        bool               `json:"archived"`
	Disabled        bool               `json:"disabled"`
	Fork            bool               `json:"fork"`
	StargazersCount int32              `json:"stargazers_count"`
	PushedAt        pgtype.Timestamptz `json:"pushed_at"`
	SourceType      string             `json:"source_type"`
	OrgID           pgtype.UUID        `json:"org_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
